{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sergeydevjava",
    "module": "logging-starter",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 1208,
          "sha512": "8fab15075c9a050df964d0ddc88aac26c53c32bfd352a012e37302cf388df07745dba51e0b20641bdbbe8a151284a3153718ebf23b5313216d200f098a43e64d",
          "sha256": "55301204207ed001f375806293dcf8a93f28f506cf026af95a8cd7276d1fb85b",
          "sha1": "81ddc2459212c637e88ab32ccbeda7004647f27c",
          "md5": "1f33e214096de30ec2eaa8fd43695c97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 1208,
          "sha512": "8fab15075c9a050df964d0ddc88aac26c53c32bfd352a012e37302cf388df07745dba51e0b20641bdbbe8a151284a3153718ebf23b5313216d200f098a43e64d",
          "sha256": "55301204207ed001f375806293dcf8a93f28f506cf026af95a8cd7276d1fb85b",
          "sha1": "81ddc2459212c637e88ab32ccbeda7004647f27c",
          "md5": "1f33e214096de30ec2eaa8fd43695c97"
        }
      ]
    }
  ]
}
